# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sapl.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasaLegislativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=100, verbose_name='Sigla')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=100, verbose_name='CEP')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PR', 'Paraná'), ('PB', 'Paraíba'), ('PA', 'Pará'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins'), ('EX', 'Exterior')], max_length=100, verbose_name='UF')),
                ('telefone', models.CharField(blank=True, max_length=100, verbose_name='Telefone')),
                ('fax', models.CharField(blank=True, max_length=100, verbose_name='Fax')),
                ('logotipo', models.ImageField(blank=True, upload_to=sapl.base.models.get_casa_media_path, verbose_name='Logotipo')),
                ('endereco_web', models.URLField(blank=True, max_length=100, verbose_name='HomePage')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-mail')),
                ('informacao_geral', models.TextField(blank=True, max_length=100, verbose_name='Informação Geral')),
            ],
            options={
                'verbose_name': 'Casa Legislativa',
                'verbose_name_plural': 'Casa Legislativa',
            },
        ),
        migrations.CreateModel(
            name='ProblemaMigracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Objeto')),
                ('nome_campo', models.CharField(blank=True, max_length=100, verbose_name='Nome do(s) Campo(s)')),
                ('problema', models.CharField(max_length=300, verbose_name='Problema')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('eh_stub', models.BooleanField(verbose_name='É stub?')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Tipo de Content')),
            ],
            options={
                'verbose_name': 'Problema na Migração',
                'verbose_name_plural': 'Problemas na Migração',
            },
        ),
    ]
